### ISSUE TITLE
Alexnet CIFAR10 checkpoints don't load properly 

### ISSUE THREAD

**Issue by synchro--** [bearpaw/pytorch-classification#11]
Hi, 
I've downloaded the checkpoints from your Onedrive about Alexnet CIFAR10  Bash recognize them as data and not tar archive,  and in fact, you can load them directly in PyTorch and it will display all the weights tensors. 
Maybe there was a mistake during the compression? 

Anyway, when I load the state_dict (for both checkpoints) this error shows up: 
```
 model = alexnet() 
 model.load_state_dict(torch.load('model_best.pth'))
 
 KeyError: 'unexpected key "acc" in state_dict'

```

Update: sorry for closing/reopening.

**Comment by bearpaw** [comment]
You should load 'model_best.pth.tar' directly.
FYI, you can use the `--resume` argument to load a checkpoint, as in the code: https://github.com/bearpaw/pytorch-classification/blob/master/cifar.py#L177-L187

**Comment by synchro--** [comment]
Thank you for the link. Now I got it. I was testing it on a personal script so I didn't look at the options.
