### ISSUE TITLE
ImportError: No module named progress.bar

### ISSUE THREAD

**Issue by zorrocai** [bearpaw/pytorch-classification#15]
In the file  /utils/__init__.py, it seems that there is a spare dot in the code:
from progress**.**bar import Bar as Bar

May it should be changed into "from progressbar import Bar as Bar"?

**Comment by GuanhuaWang** [comment]
I got the same error

**Comment by bearpaw** [comment]
Hi all,

Please see https://github.com/bearpaw/pytorch-pose/issues/62

**Comment by GuanhuaWang** [comment]
Cool, it works for me. maybe you can close this issue. Thx.
