### ISSUE TITLE
about imagenet training

### ISSUE THREAD

**Issue by amiltonwong** [bearpaw/pytorch-classification#2]
Hi, @bearpaw ,

According imagenet [training](https://github.com/bearpaw/pytorch-classification/blob/master/TRAINING.md#resnet-18),  you mention `--data` option is `~/dataset/ILSVRC2012/`. However, after I download the ILSVRC17 dataset `ILSVRC2017_CLS-LOC.tgz` from current year challenge.
![ilsvrc17_download](https://user-images.githubusercontent.com/2517000/27170659-4bea80be-51e1-11e7-8afc-d0ffe2e96e7a.png)

The *.JPEG are located inside train/val/test at the following folder structures:

~/dataset/ILSVRC/
------------------------Data/
-------------------------------CLS-LOC/
--------------------------------------------train/
--------------------------------------------------n01440764/*.JPEG
--------------------------------------------------n01443537/*.JPEG
...

------------------------------------------- val/
------------------------------------------- test/

Any suggestions to modify `--data` option in imagenet training?

THX!

**Comment by bearpaw** [comment]
Hi @amiltonwong ,
I only test the code on ILSVRC12 dataset. I follow [this instruction](https://github.com/facebook/fb.resnet.torch/blob/master/INSTALL.md#download-the-imagenet-dataset) to preprocess the data. It might also work for ILSVRC17 data.
