### ISSUE TITLE
Why did you use Basic Block and Bottleneck Block?

### ISSUE THREAD

**Issue by PabloRR100** [bearpaw/pytorch-classification#25]
Hi Bearpaw, 

Nice implementation!
However, in the paper the authors for CIFAR10 just pad the input to match the dimensions before the summation if there was a downsampling - every 2n layers.

Why did you make use of Basic Block until layer 44 and Bottleneck Block beyond that?

Regards,
Pablo

**Comment by PabloRR100** [comment]
In fact, this implementation of ResNet20 leads to 0.85M parameters where the reported is 0.27M.
What could it be?

**Comment by bearpaw** [comment]
Sorry, this was a mistake and has been fixed in the latest commit. 

In this commit, we allow users to choose the type of blocks (basicblock vs bottleneck). So you can roll back to the original experiments by using basicblock. You can also explore more with bottleneck :)
