### ISSUE TITLE
Mean and Std in Normalization

### ISSUE THREAD

**Issue by adarsh-kr** [bearpaw/pytorch-classification#28]
I have a quick question regarding normalization transform. The mean and Std which is being used [here](https://github.com/bearpaw/pytorch-classification/blob/master/cifar.py#L114), are calculated for CIFAR dataset or ImageNet dataset?
I saw a repo which was using the same values for ImageNet dataset.

**Comment by HolmesShuan** [comment]
The same question was asked [here](https://github.com/kuangliu/pytorch-cifar/issues/8).
