### ISSUE TITLE
accuracy rate of resnet-110 on cifar-100

### ISSUE THREAD

**Issue by cupwater** [bearpaw/pytorch-classification#29]
Hi, I have trained resnet-110 on cifar-100, and I got a 77% test acc, which outperformed the result you reported result by 5 percents ( 77%(my result) v.s. 71.2%(you reported) ). I have not modified any code and configs. So, I'm really interested in how you get the result you reported?

**Comment by hukkai** [comment]
Hello, I cannot get the 77% test acc for res110 as you mentioned and 77% for pre-resnet110 the author reported. I can only get 72%.  Could you give me some hints about the dropped accuracy? I use PyTorch 1.1 and 1080Ti
