### ISSUE TITLE
would you release the imagenet pretrain model and log file?

### ISSUE THREAD

**Issue by soeaver** [bearpaw/pytorch-classification#3]
thx!

**Comment by bearpaw** [comment]
Hi @soeaver , please find the trained models and the training logs at https://github.com/bearpaw/pytorch-classification#pretrained-models . Thanks.

**Comment by soeaver** [comment]
@bearpaw Thanks for your valuable work again.
I use your code to train resnet18 on imagenet, and get the same val-acc as yours(30.09%,top1-error).
But I divide the lr by 10 at 91 epoch, and continue training the network for extra 20 epochs, the val-acc gets better than before. Finally, I get 29.498%-top1-error and 10.552%-top5-error. I think this experience will have a little help.
![image](https://user-images.githubusercontent.com/8629203/27643547-f4801488-5c53-11e7-92c0-088e152cc860.png)

**Comment by bearpaw** [comment]
@soeaver That sounds great! It is absolutely a very valuable experience. Thanks for sharing it with us!
