### ISSUE TITLE
For vgg16, there are three classifier layers in the provided checkpoint but only one in the model

### ISSUE THREAD

**Issue by Hanson13** [bearpaw/pytorch-classification#34]
When I am loading the checkpoint of vgg16, which is downloaded from https://download.pytorch.org/models/vgg16-397923af.pth, there is an error:

> RuntimeError: Error(s) in loading state_dict for VGG:
        Missing key(s) in state_dict: "classifier.weight", "classifier.bias".
        Unexpected key(s) in state_dict: "classifier.0.weight", "classifier.0.bias", "classifier.3.weight", "classifier.3.bias", "classifier.6.weight", "classifier.6.bias".

So I find that there are three classifier layers(classifier.0\3\6) in the provided checkpoint but only one classifier layers (classifier) in the model, can anyone tell me why there is a mismatch problem?
Thank you!

**Comment by Hanson13** [comment]
The pretrained model in the model_url is for imagenet but not cifar10, so there are three fc layers in the checkpoint.

**Comment by GShef** [comment]
Hello @Hanson13 , how did u fix this?
