### ISSUE TITLE
Depth should be 6n+8 instead 6n+2 in CIFAR-10?

### ISSUE THREAD

**Issue by liuzhuang13** [bearpaw/pytorch-classification#6]
Hi, thanks for this nice code!
In my understanding, it seems that you didn't count downsampling blocks as depth 2 layers?

**Comment by liuzhuang13** [comment]
Sorry, I didn't see the "1" in "range(1, blocks)", never mind!

**Comment by luzai** [comment]
Hi~ I guess `Depth=6n+2` when using `basicblock` and `Depth=9n+2` when using `bottleneck`.  [The code here ](https://github.com/bearpaw/pytorch-classification/blob/6e1d46e36c0aec987e07789c63a2b7e9f974b494/models/cifar/resnet.py#L98) only consider `basicblock`. 

I am not sure enough about how to calculate the depth in the neural network architecture, could you give me some hints about it? 

Thanks a lot!

**Comment by luzai** [comment]
Hi~ 
I suggest change 
``` python
        assert (depth - 2) % 6 == 0, 'depth should be 6n+2'
        n = (depth - 2) // 6

        block = Bottleneck if depth >=44 else BasicBlock
```
to
``` python
        if depth >= 44:
            assert (depth - 2) % 9 == 0
            n = (depth - 2) // 9
            block = Bottleneck

        else:
            assert (depth - 2) % 6 == 0, 'depth should be 6n+2'
            n = (depth - 2) // 6
            block = BasicBlock
```

**Comment by bearpaw** [comment]
@luzai Hi. The code is based on the original ResNet implementation in Torch. You may find it here  https://github.com/facebook/fb.resnet.torch/blob/master/models/resnet.lua#L131

**Comment by luzai** [comment]
Thanks a lot! I will try to read the original implementation in detail.

**Comment by luzai** [comment]
Hi~ 
It seems that in Torch implementation they always use `basicblock` on cifar10 so they can use `local n = (depth - 2) / 6`. 
To keep consistent with original implementation, I suggest change `block = Bottleneck if depth >=44 else BasicBlock` to `block=BasicBlock` or provide a option to choose a building block for cifar10.

**Comment by bearpaw** [comment]
@luzai Thanks. Would you mind creating a pull request?

**Comment by luzai** [comment]
Thanks a lot! I will try my first pull request in my life ^_^
