### ISSUE TITLE
About the depth of resnet56 with bottleneck as building block

### ISSUE THREAD

**Issue by luzai** [bearpaw/pytorch-classification#8]
Hi~ Thanks a lot for your excellent work!

I guess after executing the code below with depth = 56, we get n =  9, block = Bottleneck. But if fact, Bottleneck contains 3 conv, the number of weighted layer is `9*9+2 = 83` instead of `6*9+2 = 56`. 

``` python
        assert (depth - 2) % 6 == 0, 'depth should be 6n+2'
        n = (depth - 2) // 6

        block = Bottleneck if depth >=44 else BasicBlock
```
Thus, I suggest change it to make sure the number of parameters keep the same. 

``` python
        if depth >= 44:
            assert (depth - 2) % 9 == 0
            n = (depth - 2) // 9
            block = Bottleneck

        else:
            assert (depth - 2) % 6 == 0, 'depth should be 6n+2'
            n = (depth - 2) // 6
            block = BasicBlock
```

**Comment by bearpaw** [comment]
Sorry for the SO late response. I have merged your PR. 

Thanks again for your contribution! 

Peace~
